---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: myproject-ci-cd
    dev_namespace: myproject-dev
    test_namespace: myproject-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
